# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/FN-Inbox
    docker:
      - image: circleci/python:2.7.14

    environment:
      TZ: "/usr/share/zoneinfo/UTC"
      PKG_VERSION: git

    steps:
      - checkout

      - run:
          name: Install postgres
          command: |
            sudo apt-get install apt-transport-https software-properties-common
            #sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main"
            sudo add-apt-repository "deb [check-valid-until=no] http://archive.debian.org/debian/dists/ jessie-backports main"
            # Disable expired Let'sEncrypt DST Root CA X3 certificate
            # https://unix.stackexchange.com/questions/671851/how-to-deal-with-www-postgres-org-certificate-expired
            sudo sed -i 's/mozilla\/DST_Root_CA_X3.crt/!mozilla\/DST_Root_CA_X3.crt/g' /etc/ca-certificates.conf
            sudo update-ca-certificates
            #wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
            
            # get the signing key and import it
            wget https://www.postgresql.org/media/keys/ACCC4CF8.asc
            sudo apt-key add ACCC4CF8.asc
            
            #sudo tee /etc/apt/sources.list.d/pgdg.list
            #echo "deb [trusted=yes] http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main"
            
            #sudo apt install curl ca-certificates gnupg
            #curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null
            #sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
            #sudo sh -c 'echo deb [check-valid-until=no] http://archive.debian.org/debian/dists/ jessie-backports main'
            
            # fetch the metadata from the new repo
            sudo apt-get update
            sudo apt-get install postgresql-13
