# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/FN-Inbox
    docker:
      - image: circleci/python:2.7.14

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: cimg/postgres:13.7

    environment:
      TZ: "/usr/share/zoneinfo/UTC"
      PKG_VERSION: git

    steps:
      - checkout

      - run:
          name: Install postgres
          command: |
            sudo apt-get -y install bash-completion wget ca-certificates
            sudo apt-get install apt-transport-https software-properties-common ca-certificates
           
