# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/FN-Inbox
    docker:
      - image: circleci/python:2.7.14
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: cimg/postgres:13.10
        environment:
          PGHOST: localhost
          POSTGRES_USER: postgres

    environment:
      TZ: "/usr/share/zoneinfo/UTC"
      PKG_VERSION: git

    steps:
      - checkout

      - run:
          name: Install postgres
          command: |
            #sudo apt-get -y install wget ca-certificates
            # Remove old repository url
            sudo rm /etc/apt/sources.list
            
            # postgres-13
             
            # fetch the metadata from the new repo
            sudo apt-get update
            
            sudo whoami
            sudo psql \
            -d $TEST_DATABASE_URL \
            -c "CREATE TABLE test (name char(25));"
            sudo psql \
            -d $TEST_DATABASE_URL \
            -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
            
