# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/FN-Inbox
    docker:
      - image: circleci/python:2.7.14

    environment:
      TZ: "/usr/share/zoneinfo/UTC"
      PKG_VERSION: git

    steps:
      - checkout

      - run:
          name: Install postgres
          command: |
            sudo apt-get install apt-transport-https software-properties-common lsb-release ca-certificates
            sudo rm /etc/apt/sources.list
            sudo cat /etc/*release
            #sudo add-apt-repository "deb https://apt.postgresql.org/pub/repos/apt/ focal-pgdg main"
            # Disable expired Let'sEncrypt DST Root CA X3 certificate
            # https://unix.stackexchange.com/questions/671851/how-to-deal-with-www-postgres-org-certificate-expired
            sudo sed -i 's/mozilla\/DST_Root_CA_X3.crt/!mozilla\/DST_Root_CA_X3.crt/g' /etc/ca-certificates.conf
            sudo update-ca-certificates
            # get the signing key and import it
            wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
            
            # get the signing key and import it
            #wget https://www.postgresql.org/media/keys/ACCC4CF8.asc
            #sudo apt-key add ACCC4CF8.asc
            
            #sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A
            #sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
            #sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9
            #sudo sh -c 'echo "deb [trusted=yes] http://apt.postgresql.org/pub/repos/apt/ lsb_release -cs-pgdg main" >> sudo tee -a /etc/apt/sources.list.d/pgdg.list'
            #echo "deb [trusted=yes] http://ftp.fr.debian.org/debian/ stretch main" | sudo tee -a /etc/apt/sources.list
            #echo "deb-src [trusted=yes] http://ftp.fr.debian.org/debian/ stretch main" | sudo tee -a /etc/apt/sources.list
            #echo "deb [trusted=yes] http://security.debian.org/debian-security stretch/updates main" | sudo tee -a /etc/apt/sources.list
            #echo "deb-src [trusted=yes] http://security.debian.org/debian-security stretch/updates main" | sudo tee -a /etc/apt/sources.list
            
            
            sudo apt-get update && apt-get install -y gnupg2 wget lsb-release
            wget -O /usr/share/keyrings/freeswitch-archive-keyring.gpg https://files.freeswitch.org/repo/deb/debian-release/freeswitch-archive-keyring.gpg

            echo "deb [signed-by=/usr/share/keyrings/freeswitch-archive-keyring.gpg] https://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" > sudo tee -a /etc/apt/sources.list.d/freeswitch.list
            echo "deb-src [signed-by=/usr/share/keyrings/freeswitch-archive-keyring.gpg] https://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" >> sudo tee -a /etc/apt/sources.list.d/freeswitch.list

            # you may want to populate /etc/freeswitch at this point.
            # if /etc/freeswitch does not exist, the standard vanilla configuration is deployed
            apt-get update && apt-get install -y freeswitch-meta-all
            
            # fetch the metadata from the new repo
            sudo apt-get update && sudo apt-get -y upgrade
            #sudo apt-get -y install postgresql
            sudo apt install sysstat postgresql-13
            #echo '/usr/lib/postgresql/9.6/bin/:$PATH' >> $BASH_ENV
